# Numpy Array functions

# Search
Search array : Search an array for a certain array for a certain value and return the indexes that get a match in any dimensions. And use keyword where

In [3]:
import numpy as np

arr = np.array([1,2,3,5,7,6,78,4,90,33,55,6,3,7,7,9,4])
x = np.where( arr == 7)
print(x)
print()
x1 = np.where( (arr%2) == 0)
print(x1)

(array([ 4, 13, 14]),)

(array([ 1,  5,  6,  7,  8, 11, 16]),)


Search sorted array: In this, we insert an element in a sorted array perform a binary search in the array and return the index where the specified value would be inserted.

In [20]:
var = np.array([1,2,3,4,7,8,9])
x = np.searchsorted( var,5,side = "right")
print(x)
print()
x1 = np.searchsorted( var,[5,6],side = "right") #pass a list
print()
print(x1)

4


[4 4]


# Sort 

Sorted array: Ordered sequence is any sequences that has an order corresponding to the elements like number or alphabetical ascending or descending.

In [27]:
s_arr = np.array([1,2,3,5,7,6,78,4,90,33,55,6,3,7,7,9,4])
arr1d = np.sort( s_arr)
print(arr1d)

[ 1  2  3  3  4  4  5  6  6  7  7  7  9 33 55 78 90]


In [29]:
arr = np.array(["a","h","k","y","g"])
arr1d = np.sort(arr)
print(arr1d)

['a' 'g' 'h' 'k' 'y']


In [35]:
var = np.array([[4,2,99],[3,2,3],[4,7,8],[9,12,98]])
arr1d = np.sort( var)
print(arr1d)

[[ 2  4 99]
 [ 2  3  3]
 [ 4  7  8]
 [ 9 12 98]]


# Filter 
Filter array: In a pre-existing matrix creating a new array will take some elements out of them. For this, we need true and false for which we need an element and for which we don't need an element respectively.

In [11]:
s_arr = np.array([1,2,3,5,4])
f = [True,False,False,True,True]

new_var = s_arr[f]
print(new_var)
print(type(new_var))

[1 5 4]
<class 'numpy.ndarray'>


# Some more Functions

# Shuffle

In [24]:
sh_arr = np.array([66,4,2,6,3,9,56,78,2,34,23,799])
np.random.shuffle(sh_arr) #every time the data will get shuffled 
print(sh_arr)

[  2   9  23  56   6   2   4  66  34 799  78   3]


# Unique

In [34]:
#gets a unique and sorted array and the return index will give an index of each element and the count will give how many
#  times each element has been occurred 

sh_arr = np.array([66,4,77,2,9,56,77,4,43,43,2,66,2,34,49,23])
x = np.unique(sh_arr,return_index = True,return_counts = True) 
print(x)

(array([ 2,  4,  9, 23, 34, 43, 49, 56, 66, 77]), array([ 3,  1,  4, 15, 13,  8, 14,  5,  0,  2]), array([3, 2, 1, 1, 1, 2, 1, 1, 2, 2]))


# Resize

In [55]:
re_arr = np.array([1,2,3,4,5,6])
y = np.resize(re_arr,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


# Flatten and Ravel
Both are performed in 2d array to convert into 1d array

In [76]:
re_arr = np.array([1,2,3,4,5,6])
y = np.resize(re_arr,(2,3))
print(y)

print()
print(y.flatten()) #After the resizing the array back to 1d array using flatten
print()
print(y.flatten(order = "c")) #  order c means row wise WHICH is default
print() 
print("Faltten order : ",y.flatten(order = "F"))  #  order F means col wise
print()
print("Ravel order : ",y.ravel())
print()
print("Ravel order : ",y.ravel(order = "A")) #Fistly it will check the order then weather it is r or c and it will convert into vise versa

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

[1 2 3 4 5 6]

Faltten order :  [1 4 2 5 3 6]

Ravel order :  [1 2 3 4 5 6]

Ravel order :  [1 2 3 4 5 6]


# Insert and Delete in array 

In [129]:
ins_arr = np.array([1,2,3,4,5,6])

print(ins_arr)
print()
v = np.insert(ins_arr,4,44)
print(v)
print()
float_val = np.insert(ins_arr,4,9.5) #insert only numerical value no decimal value will be inserted
print(float_val)
print()
float_val = np.append(ins_arr,9.5) # inserting using append function but you cnt give the index 
print(float_val)

[1 2 3 4 5 6]

[ 1  2  3  4 44  5  6]

[1 2 3 4 9 5 6]

[1.  2.  3.  4.  5.  6.  9.5]


In [139]:
ins_arr2d = np.array([[1,2,3],[4,5,6]])
v2d = np.insert(ins_arr2d,3,4,axis = 1)
print(ins_arr2d)
print()
print(v2d)
v2 = np.insert(ins_arr2d,2,[4,8,9],axis = 0) #inserted list 
print()
print(v2)
print()
float_val = np.append(ins_arr2d,[[7,2,2]],axis = 0) # inserting using append function but you cnt give the index 
print(float_val)


[[1 2 3]
 [4 5 6]]

[[1 2 3 4]
 [4 5 6 4]]

[[1 2 3]
 [4 5 6]
 [4 8 9]]

[[1 2 3]
 [4 5 6]
 [7 2 2]]


In [149]:
# Delete in array 
del_arr = np.array([1,52,36,46,57,6])

print(del_arr)
print()
v =  np.delete(del_arr,3)
print(v)


[ 1 52 36 46 57  6]

[ 1 52 36 57  6]


# Matix in array 

In [154]:
matriz_arr = np.matrix([1,52,36,46,57,6]) # matrix
print(matriz_arr)
print(type(matriz_arr))

[[ 1 52 36 46 57  6]]
<class 'numpy.matrix'>


In [158]:
arr = np.array([1,52,36,46,57,6]) #array
print(arr)
print(type(arr))

[ 1 52 36 46 57  6]
<class 'numpy.ndarray'>


# Addition in matrix

In [161]:
matriz_arr = np.matrix([1,52,36,46,57,6]) # matrix
matriz_arr2 = np.matrix([1,52,36,46,57,6])

var = (matriz_arr + matriz_arr2)
print(var)
print(type(var))

[[  2 104  72  92 114  12]]
<class 'numpy.matrix'>


# Subtraction in matix 

In [166]:
matriz_arr = np.matrix([1,52,36,46,57,6]) # matrix
matriz_arr2 = np.matrix([0,23,6,4,5,18])

var = (matriz_arr - matriz_arr2)
print(var)
print(type(var))

[[  1  29  30  42  52 -12]]
<class 'numpy.matrix'>


# Multiplication in matrix 

In [175]:
matriz_arr = np.matrix([[1,52],[5,4]]) # matrix
matriz_arr2 = np.matrix([[0,23],[9,6]])

var = (matriz_arr * matriz_arr2)
print(var)
print(type(var))


[[468 335]
 [ 36 139]]
<class 'numpy.matrix'>


In [188]:
matriz_arr = np.matrix([[5,10],[2,4]]) # matrix
matriz_arr2 = np.matrix([[2,2],[9,6]])
# using dot function 
print(matriz_arr.dot(matriz_arr2))
print(type(matriz_arr.dot(matriz_arr2)))

[[100  70]
 [ 40  28]]
<class 'numpy.matrix'>


# Multiplication in array with same above 

In [194]:
matriz_arr = np.array([[5,10],[2,4]]) # matrix
matriz_arr2 = np.array([[2,2],[9,6]])
# using dot function 
print(matriz_arr * matriz_arr2)
print(type(matriz_arr * matriz_arr2)) # both multiplication in array and matrix is different 

[[10 20]
 [18 24]]
<class 'numpy.ndarray'>


# Transpose of matrix 

In [216]:
t_arr = np.matrix([[5,10],[2,4]])
print(t_arr)
print(t_arr.ndim)
print()
print(np.transpose(t_arr))
print()
print(t_arr.T) # alternative FOR transpose

[[ 5 10]
 [ 2  4]]
2

[[ 5  2]
 [10  4]]

[[ 5  2]
 [10  4]]


# Swap axis in array 

In [222]:
s_arr = np.array([[5,10],[2,4]])
print(s_arr)
print()
print(np.swapaxes(s_arr,0,1))

[[ 5 10]
 [ 2  4]]

[[ 5  2]
 [10  4]]


# Swap axis in martix

In [224]:
s_arr = np.matrix([[54,150],[82,477]])
print(s_arr)
print()
print(np.swapaxes(s_arr,0,1))

[[ 54 150]
 [ 82 477]]

[[ 54  82]
 [150 477]]


# Inverse of matrix 

In [227]:
i_arr = np.matrix([[1,2],[3,4]])
print(i_arr)
print()
print(np.linalg.inv(i_arr))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power of matrix

In [234]:
p_arr = np.matrix([[1,2],[3,4]])
print(p_arr)
print()
print(np.linalg.matrix_power(p_arr,3)) # when n > 0
print()
print(np.linalg.matrix_power(p_arr,0)) # when n  = 0 identity matrix
print()
print(np.linalg.matrix_power(p_arr, -2)) # when n  < 0

[[1 2]
 [3 4]]

[[ 37  54]
 [ 81 118]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


# Determinate of matrix

In [239]:
d_arr = np.matrix([[1,2],[3,4]])
print(d_arr)
print()
print(np.linalg.det(d_arr))

[[1 2]
 [3 4]]

-2.0000000000000004


In [259]:
d_arr = np.matrix([[5,2],[7,4]])
print(d_arr)
print()
print(np.linalg.det(d_arr))

[[5 2]
 [7 4]]

5.999999999999997


In [269]:
d_arr = np.matrix([[1,2,5],[3,6,3],[5,5,4]])
print(d_arr)
print()
print(np.linalg.det(d_arr))

[[1 2 5]
 [3 6 3]
 [5 5 4]]

-59.999999999999986
