# Broadcasting in Numpy Array

We need to compare the row and column to perform broadcasting.
NumPy treats arrays with different shapes during arithmetic operations. 
The smaller array broadcasts into a larger array to get the compatible array.
We compare 2D Array we need to rules 
1. Shapes are equal, or
2. one of them is 1(either of row or column)


In [2]:
import numpy as np
var1 = np.array([1,2,3,4]) # 1d with same dimension

var2 = np.array([1,2,3,5])

print(var1+var2)


[2 4 6 9]


In [20]:
var1 = np.array([1,2,3,4]) 
print(var1.shape)
print()
var2 = np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var1+var2)# adding with different shape

(4,)

(3, 1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [26]:
var1 = np.array([1,2,3]) 
print(var1.shape)
print()
var2 = np.array([[1]])
print(var2.shape)
print()
print(var1+var2)
print()
print((var1+var2).shape)# adding with different shape ()

(3,)

(1, 1)

[[2 3 4]]

(1, 3)


# Indexing in Numpy Array
The index will determine the position of an element in the array.
Index for an array can be _ve or +ve.

In [39]:
arr_1D = np.array([1,2,3,4,5])

print(arr_1D[3]) # it will print 4 as its index is 3
print()
print(arr_1D[-2]) # it will print 4 as its index is -2

4

4


In [53]:
arr_2d = np.array([[4,5,6] , [6,7,8]])
print(arr_2d)
print(arr_2d.shape)
print()
print(arr_2d[1,2]) # 2d index to find value 8

[[4 5 6]
 [6 7 8]]
(2, 3)

8


In [61]:
arr_3d = np.array([[[4,5,6] , [6,7,8]],[[1,2,4],[7,9,0]]])
print(arr_3d)
print(arr_3d.shape)
print()
print(arr_3d[1,0,1]) # 3d index to find value 2
print(arr_3d[1,1,2]) # 3d index to find value 0
print(arr_3d[0,1,0]) # 3d index to find value 6

[[[4 5 6]
  [6 7 8]]

 [[1 2 4]
  [7 9 0]]]
(2, 2, 3)

2
0
6


# Slicing in Numpy array

Syntax : Slicing [Start:stop:step] always stop will be added +1 while indexing as index start with 0

In [76]:
x = np.array([1,2,3,4,5,6,7,8,9,10]) # 1d with same dimension slicing
 #            0,1,2,3,4,5,6,7,8,9 index of element
print(x)
print()
print("2 to 5 : ",x[1:5]) 
print()
print("2 to last element : ",x[1:]) 
print()
print("start to 5t element : ",x[:5]) 
print()
print("stop : ",x[::2])  # step value is 2 and it will show 2nd value after 2 jump
print()
print("stop : ",x[::6])  # step value is 6 and it will show 2nd value after 6jump

[ 1  2  3  4  5  6  7  8  9 10]

2 to 5 :  [2 3 4 5]

2 to last element :  [ 2  3  4  5  6  7  8  9 10]

start to 5t element :  [1 2 3 4 5]

stop :  [1 3 5 7 9]

stop :  [1 7]


In [94]:
# slicing in 2d array
x_2d = np.array([[1,7,9,0,8,6],[6,8,9,4,2,4],[4,5,7,8,6,9]])
print()
print("5 to 9 : ",x_2d[2,1:]) 
print()
print("6 to 4 : ",x_2d[1,0:]) 
print()

print("7 to 9 : ",x_2d[0,1:3]) 

print()
print("6 to 4 : ",x_2d[1,0:]) 
print()
print("6 to 2 with step 2 : ",x_2d[1,0::2]) 


5 to 9 :  [5 7 8 6 9]

6 to 4 :  [6 8 9 4 2 4]

7 to 9 :  [7 9]

6 to 4 :  [6 8 9 4 2 4]

6 to 2 with step 2 :  [6 9 2]


# Iteration in Numpy array

In [101]:
#Iteration in 1D Array
arr_1d = np.array([9,8,7,6,5,4,3,2,1,0])
for i in arr_1d:
    print(i)
                  

9
8
7
6
5
4
3
2
1
0


In [107]:
#Iteration in 2D Array
arr_2d = np.array([[9,8,7,6,5,4,3],[2,5,7,9,8,7,7]])
for i in arr_2d:
    for j in i:
         print(j)
   

9
8
7
6
5
4
3
2
5
7
9
8
7
7


In [109]:
#Iteration in 3D Array
arr_3d = np.array([[[1,2,3],[4,5,6]]])
for i in arr_3d:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6


In [117]:
#If we dnt want to use iteration using for loop use nditer() function

#Iteration in 3D Array using nditer fun
arr_3d = np.array([[[1,2,3],[4,5,6]]])
for i in np.nditer(arr_3d,flags=['buffered'],op_dtypes = ['S']): # changed the data type in string and stored in buffer
    print(i)
    

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [121]:
arr_3d = np.array([[[1,2,3],[4,5,6]]])
for i in np.ndenumerate(arr_3d): # to print the index value and elements in array
    print(i)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)


# copy vs view

In [126]:
var_1 = np.array([1,4,5,6,7,0])

co = var_1.copy() # copy function
print("var :  ", var_1)
print("co :  ", co)

var :   [1 4 5 6 7 0]
co :   [1 4 5 6 7 0]


In [137]:
var_1 = np.array([1,4,5,6,7,0])

vw = var_1.view() # view function
print("var :  ", var_1)
print("co :  ", vw)

var :   [1 4 5 6 7 0]
co :   [1 4 5 6 7 0]


The difference between copy works in own data and view works in original data.
The copy of an array is a new array. The view is the original array.
The changes made in the copy do not reflect in the original data. But in view, it will affect.

In [133]:
var_1 = np.array([1,4,5,6,7,0])

co = var_1.copy() # copy function
var_1[1] = 30
print("var :  ", var_1) # only original data changes not copy 
print("co :  ", co)

var :   [ 1 30  5  6  7  0]
co :   [1 4 5 6 7 0]


In [139]:
var_1 = np.array([1,4,5,6,7,0])

vw = var_1.view() # view function
var_1[3]= 99
print("var :  ", var_1)
print("co :  ", vw)

var :   [ 1  4  5 99  7  0]
co :   [ 1  4  5 99  7  0]


# Join & Split function 
Joining means putting the contents of two or more arrays in a single array. No of elements should be same.

In [8]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

arr_new = np.concatenate((var1,var2)) # 1d array
print(arr_new)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
# 2d array using concatenate function
ar1 = np.array([[1,2,],[4,5]])
ar2 = np.array([[6,7],[9,10]])

arr_new2d = np.concatenate((ar1,ar2),axis = 1) # concate with row
print(arr_new2d)
print(arr_new2d.ndim)
print()
arr_new3d = np.concatenate((ar1,ar2),axis = 0) # concate with column
print(arr_new3d)
print(arr_new3d.ndim)

[[ 1  2  6  7]
 [ 4  5  9 10]]
2

[[ 1  2]
 [ 4  5]
 [ 6  7]
 [ 9 10]]
2


In [30]:
# using stack function
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

ar_new = np.stack((arr1,arr2),axis =1) # column
print(ar_new)
print(ar_new.ndim)
print()
ar1_new = np.stack((arr1,arr2),axis =0) #row
print(ar1_new)
print(ar1_new.ndim)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
2

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [34]:
# using stack function wihtout defining axis in array 
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

column_arr = np.vstack((arr1,arr2)) # column
print(column_arr)
print(column_arr.ndim)
print()
row_arr = np.hstack((arr1,arr2)) #row
print(row_arr)
print(row_arr.ndim)
print()
height_arr = np.dstack((arr1,arr2)) #height
print(height_arr)
print(height_arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2

[ 1  2  3  4  5  6  7  8  9 10]
1

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]
3


# Splitting the array in different dimension 

In [43]:
arr = np.array([1,2,3,4,5,6])

print(arr)
print()
sp_srr = np.array_split(arr,3)
print(sp_srr)

print(type(sp_srr))
print(sp_srr[1]) # printing with index value

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[3 4]


In [53]:
arr2d = np.array([[1,2],[3,4],[5,6]])

print(arr2d)
print()
sp_srr = np.array_split(arr2d,3)
print(sp_srr)
print()
sp_srr_ax = np.array_split(arr2d,3,axis = 1)
print(sp_srr_ax)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]
