# Numpy Array

In [16]:
import numpy as np

In [18]:
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [20]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [22]:
%timeit [j**4 for j in range(1,9)]

287 ns ± 7.58 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
%timeit np.arange(1,9)**4

915 ns ± 8.17 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Creating an array in empty list

In [25]:
L = []
for i in range(1,5):
    values = int(input("enter : ")) #added an int type data to our input else it will be string type
    L.append(values)

print(np.array(L))

enter :  2
enter :  2
enter :  2
enter :  2


[2 2 2 2]


# Dimensions in array
 1D Array -> [1 2 3 4]  ,
 2D Array -> [[1 2 3 4 ]] ,
  3D Array -> [[[1 2 3 4 ]]],
 Higher Dimension array

To know the dimension of array use ndim 
 

In [34]:
array_1D = np.array([1,2,3,4])
print(array_1D)
print(array_1D.ndim) # To find the Dimension of the array 

[1 2 3 4]
1


In [36]:
array_2D = np.array([[1,2,3,4], [2,3,4,5]]) #To create 2d array no of elements in array should be same.
print(array_2D)
print(array_2D.ndim) # To find the Dimension of the array 

[[1 2 3 4]
 [2 3 4 5]]
2


In [38]:
array_3D = np.array([[[1,2,3,4], [2,3,4,5],[3,4,5,6]]]) #To create 3d array no of elements in the array should be the same.
print(array_3D)
print(array_3D.ndim) # To find the Dimension of the array 

[[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]]
3


In [46]:
array_multi = np.array([1,2,3,4], ndmin = 12) # to create multi-dimension arr use ndimn and any value can be given
print(array_multi)
print(array_multi.ndim)

[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]
12


# Create a numpy array using numpy function

Create an array with all no zeros

In [50]:
arr_zero = np.zeros(4) #Single dimension array with all value as 0
print(arr_zero)
print(arr_zero.ndim)

[0. 0. 0. 0.]
1


In [56]:
arr_zero2 = np.zeros((3,4)) #2 dimension array with all value as 0
print(arr_zero2)
print(arr_zero2.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


Create an array with all number as 1's

In [68]:
arr_one = np.ones(4) #1 dimension array with all value as 0
print(arr_one)
print(arr_one.ndim)

[1. 1. 1. 1.]
1


In [70]:
arr_one = np.ones((4,4)) #2 dimension array with all value as 0
print(arr_one)
print(arr_one.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


To create empty array

In [77]:
arr_em = np.empty(3) # use previous memory and print the data
print(arr_em)

[3. 2. 1.]


To create a range array.


In [82]:
arr_rn = np.arange(7) # print the data from a range , values starts from 0
print(arr_rn)

[0 1 2 3 4 5 6]


To create a diagonal matrix of value 1


In [85]:
arr_dia = np.eye(5) # use eye method this create as 5*5 matrix
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [93]:
arr_dia = np.eye(3,4) # to create random matrix with 2d array
print(arr_dia)
print(arr_dia.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
2


To create space in line with specific interval of matrix use linspace

In [96]:
arr_ln = np.linspace(0,10, num = 5) # Give a range of value and then give num to add a space acc to need
print(arr_ln)
print(arr_ln.ndim)

[ 0.   2.5  5.   7.5 10. ]
1


In [98]:
arr_ln = np.linspace(0,20, num = 5) 
print(arr_ln)
print(arr_ln.ndim)

[ 0.  5. 10. 15. 20.]
1


In [102]:
arr_ln = np.linspace(0,20, num = 4) # Give a range of value and then give num to add a space acc to need
print(arr_ln)
print(arr_ln.ndim)

[ 0.          6.66666667 13.33333333 20.        ]
1


# To create numpy array with a Random Array 

1. rand() -> This function is used to generate a random value between 0 to 1.
2. randn() -> This function is used to generate a random value close to 0. This may return -ve or +ve numbers as well.
3. ranf()-> This function is used for sampling in numpy and returns an array of specific shapes which fills with random floats in the happen interval [0.0, 1.0). Means 0 in included but not 1.
4. randint() -> This function is used to generate a random value between a given range.

In [110]:
arr_ran = np.random.rand(5) # example 1.  [0.81259334 0.39960226 0.88529534 0.30581452 0.34635141] this is 1-D array
print(arr_ran)              # example 2.  [0.03881033 0.89007407 0.15592176 0.89567929 0.23890793]
print(arr_ran.ndim)

[0.11054616 0.52573119 0.82960356 0.24059092 0.16987783]
1


In [112]:
arr_ran2 = np.random.rand(3,4) # this is 2D array for random array 
print(arr_ran2)              
print(arr_ran2.ndim)

[[0.468204   0.44202641 0.41413077 0.40946192]
 [0.62927911 0.76245324 0.21520182 0.93215378]
 [0.28323889 0.36657827 0.01140295 0.67548468]]
2


In [118]:
arr_rann = np.random.randn(5) # ex 1  [ 0.20945681 -0.37582136 -0.1433742   1.86285355  0.41120908] this is 1-D array and give -ve value
print(arr_rann)              # example 2.  [ 0.22398761 -0.06286808 -0.5703738  -0.10537787 -0.20248997]
print(arr_rann.ndim)

[ 1.43634291e+00 -9.17936804e-01  1.58986065e-03  1.77699323e+00
  8.55009459e-01]
1


In [126]:
arr_rann2 = np.random.randn(2,5) # 2-D array
print(arr_rann2)              
print(arr_rann2.ndim)

[[-0.40276822  0.7089646  -0.71385413 -0.02920615  0.51043487]
 [ 0.73867265  0.72383149  0.65065626 -2.28199694  0.27977155]]
2


In [135]:
arr_ranf = np.random.ranf(5) # 1-D array using ranf
print(arr_ranf)              
print(arr_ranf.ndim)

[0.0464398  0.53949155 0.84210736 0.35491344 0.11971397]
1


In [151]:
arr_ran2f = np.random.randint(0,10,5) ## values can be passed as (min,max,total value)
print(arr_ran2f)  


[9 8 2 7 3]
