**Data types in Numpy arrays**
1. int
2. bool
3. float
4. complex

To find the type of data use dtype keyword.

In [4]:
import numpy as np

var = np.array([1,2,4,3])

print(var)
print("Data type :",var.dtype) #int type data

[1 2 4 3]
Data type : int64


In [2]:
var1 = np.array([1.0,2.0,4.0,3.0])

print(var1)
print("Data type :",var1.dtype)# float type data

[1. 2. 4. 3.]
Data type : float64


In [4]:
varS = np.array(["A","B","C"])

print(varS)
print("Data type :",varS.dtype)# String type data

['A' 'B' 'C']
Data type : <U1


In [5]:
var_mix = np.array(["A","B","C",1,2,3])

print(var_mix)
print("Data type :",var_mix.dtype)# String and int type data

['A' 'B' 'C' '1' '2' '3']
Data type : <U21


To convert from one datatype to another

In [9]:
x = np.array([1,2,4,3], dtype = np.int8) #converting from int64 to int8
print(x)
print("Data type :",x.dtype)

[1 2 4 3]
Data type : int8


In [12]:
x1 = np.array([1,2,4,3], dtype = "f") #converting from int64 to float using shortcut
print("Data type :",x1.dtype)
print(x1)

Data type : float32
[1. 2. 4. 3.]


In [13]:
x1 = np.array([1,2,4,3])
new_arr = np.float32(x1) #converting from int64 to float using function
print("Data type :",x1.dtype)
print("Data type :",new_arr.dtype)
print(x1)
print(new_arr)

Data type : int64
Data type : float32
[1 2 4 3]
[1. 2. 4. 3.]


In [14]:
new_arrint = np.int_(x1) # Again we can convert back into int using funtion
print("Data type :",new_arrint.dtype)
print(new_arrint)

Data type : int64
[1 2 4 3]


In [16]:
x3 = np.array([1,2,4,3]) #Dirclty changing the data type by using astype

new_x3 = x3.astype(float)
print("Data type :",x3.dtype)
print("Data type :",new_x3.dtype)
print(x3)
print(new_x3)

Data type : int64
Data type : float64
[1 2 4 3]
[1. 2. 4. 3.]


 **Arithmetic operations in array**
 1. Add operation (a+b) -> np.add(a,b)
 2. Subtract operation (a-b) -> np.subtract(a,b)
 3. Mutliplication operation (a*b) -> np.multiply(a,b)
 4. Divide operation (a*b) -> np.divide(a,b)
 5. Mod operation (a*b) -> np.mod(a,b)
 6. Power operation (a**b) -> np.power(a,b)
 7. Reciprocal operation (a*b) -> np.reciprocal(a,b)



In [33]:
a = np.array([1,2,4,3])
a_add = a + 3 #Adding value to each element present in array
print(a_add)
print(a)

[4 5 7 6]
[1 2 4 3]


In [34]:
a1 = np.array([1,2,4,3])
a2 = np.array([8,9,2,6])
a_add = a1 + a2 #Adding two array of each element with the same index value.
print(a_add)
print(a1)
print(a2)

[ 9 11  6  9]
[1 2 4 3]
[8 9 2 6]


In [35]:
a = np.array([1,2,4,3])
a_sub = a - 3 #Subtract value to each element present in array
print(a_sub)
print(a)

[-2 -1  1  0]
[1 2 4 3]


In [36]:
a = np.array([1,2,4,3])
a_mul = a * 3 #Multiply value to each element present in array
print(a_mul)
print(a)

[ 3  6 12  9]
[1 2 4 3]


In [43]:
a = np.array([1,2,4,3])
a_dvd = a / 3 # Divide the value of each element present in array
print(a_dvd)
print(a)

[0.33333333 0.66666667 1.33333333 1.        ]
[1 2 4 3]


In [44]:
a = np.array([4,5,101,135])
a_rem = a % 3 # Getting remainder from mod operator
print(a_rem)
print(a)

[1 2 2 0]
[  4   5 101 135]


**Use function for mathematical operations**:
Which is defined above.


In [30]:
a = np.array([1,2,4,3])
a_add = np.add(a,3) #Adding value to each element present in array using add fun
print(a_add)
print(a)

[4 5 7 6]
[1 2 4 3]


In [32]:
a1 = np.array([1,2,4,3])
a2 = np.array([8,9,2,6])
a_add = np.add(a1,a2) #Adding two array of each element with the same index value using add fun
print(a_add)
print(a1)
print(a2)

[ 9 11  6  9]
[1 2 4 3]
[8 9 2 6]


In [40]:
a = np.array([4,8,4,3])
a_sub = np.subtract(a,3) #Subtract the value to each element present in array using add fun
print(a_sub)
print(a)

[1 5 1 0]
[4 8 4 3]


In [41]:
a = np.array([1,2,4,3])
a_mul =np.multiply(a,10) #Multiply the value to each element present in array using add fun
print(a_mul)
print(a)

[10 20 40 30]
[1 2 4 3]


In [42]:
a = np.array([1,2,4,3])
a_dvd =np.divide(a,10) #Divide the value to each element present in array using add fun
print(a_dvd)
print(a)

[0.1 0.2 0.4 0.3]
[1 2 4 3]


In [47]:
a = np.array([1,2,4,3])
a_res =np.reciprocal(a) #Reciporcal the value to each element present in array using add fun
print(a_res)
print(a)

[1 0 0 0]
[1 2 4 3]


Operations in 2D Array

In [50]:
var2d = np.array([[1,2,4,3],[5,6,2,7]])
var2d2 = np.array([[5,2,8,3],[5,9,2,8]])

add2D = var2d + var2d2; # adding in 2d array
print(add2D)
print()
print(var2d)
print()
print(var2d2)


[[ 6  4 12  6]
 [10 15  4 15]]

[[1 2 4 3]
 [5 6 2 7]]

[[5 2 8 3]
 [5 9 2 8]]


In [55]:
var2d = np.array([[1,2,4,3],[5,6,2,7]])
var2d2 = np.array([[5,2,8,3],[5,9,2,8]])

sub2D = var2d - var2d2; # Sub in 2d array
print(sub2D)

[[-4  0 -4  0]
 [ 0 -3  0 -1]]


In [54]:
var2d = np.array([[1,2,4,3],[5,6,2,7]])
var2d2 = np.array([[5,2,8,3],[5,9,2,8]])

mul2D = var2d * var2d2; # Multiple in  2d array
print(mul2D)

[[ 5  4 32  9]
 [25 54  4 56]]


Arithmetic function in Numpy Array

In [60]:
a_1d = np.array([4,5,2,9,0,1,33,45,88,100])
min = np.min(a_1d)
max = np.max(a_1d)
print("min : ", min, np.argmin(a_1d)) # To find the Minimum value from the array
print("min : ", max, np.argmax(a_1d)) # To find the Maximum value from the array

min :  0 4
min :  100 9


In [65]:
arr_2D = np.array([[9,5,7,6,4],[7,5,6,2,33]])

print(np.min(arr_2D,axis= 1)) # Find the min value in 2D Array within the axis 1 (means row wise)

print(np.min(arr_2D,axis= 0)) # Find the min value in 2D Array within the axis 0 (means column wise)

[4 2]
[7 5 6 2 4]


In [69]:
a_sqrt = np.array([4,5,2])
print(np.sqrt(a_sqrt)) # To find the sqrt value from the array

[2.         2.23606798 1.41421356]


In [70]:
arrM = np.array([4,5,2])
print(np.sin(arrM)) # To find the sin value from the array
print(np.cos(arrM)) # To find the cos value from the array

[-0.7568025  -0.95892427  0.90929743]
[-0.65364362  0.28366219 -0.41614684]


In [71]:
a_cumsum = np.array([4,5,2,9,0,1,33,45,88,100])
print(np.cumsum(a_cumsum)) # Added in the previous value like 0+4 ,4+5= 9 ,9+2 =11,11+9 =20 , 20+0 =20 , 20+1 = 21 ...........

[  4   9  11  20  20  21  54  99 187 287]


In [72]:
arr_cumsum = np.array([4,5,2])
print(np.cumsum(arr_cumsum)) # same as above

[ 4  9 11]


**Shape and Reshaping in Array**
1. Shape : Helps to get to know about how many rows and colums are present in array.
2. Reshape : Helps to reshape the array in any dimensions.


In [74]:
varShape = np.array([[1,2,3,1],[41,4,5,6]])
print(varShape)
print()
print(varShape.shape)

[[ 1  2  3  1]
 [41  4  5  6]]

(2, 4)


In [78]:
varMulti = np.array([1,2,6,7],ndmin= 5)
print(varMulti)
print()
print(varMulti.ndim)
print(varMulti.shape)

[[[[[1 2 6 7]]]]]

5
(1, 1, 1, 1, 4)


In [89]:
varShape = np.array([1,2,3,1,41,4,6,7])
print(varShape)
reshape_arr = varShape.reshape(4,2,) #always see the no of elements while reshaping it should be equal while apply shape else it will through error.
print()
print(reshape_arr)
print(reshape_arr.ndim)

[ 1  2  3  1 41  4  6  7]

[[ 1  2]
 [ 3  1]
 [41  4]
 [ 6  7]]
2
